version: '2'
services:
  mhacks_db:
    image: mongo
    restart: always
  mhacks_es:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.0
    environment:
      - discovery.type=single-node
    restart: always
  mhacks_website:
    build:
      context: ..
    image: mhacks_website
    environment:
      MONGO_HOSTNAME: mhacks_db
    restart: always
  mhacks_nginx:
    image: jwilder/nginx-proxy
    volumes:
      - /etc/nginx/certs
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"
      - "443:443"
    restart: always
  mhacks_nginx_letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always